### ISSUE TITLE
Add link to C By Example

### ISSUE THREAD

**Issue by seanvaleo** [MattPD/cpplinks#29]
Please consider adding a link to cbyexample.com on the `learning_teaching.md` page. Thanks.

**Comment by MattPD** [comment]
Thanks. I prefer to keep focus on the standard references or resources I've checked myself.
While looking at the suggested link I've found a few issues I'd recommend fixing:
- "Do I need to check for null before delete p?"  No, https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null
- [Nit] Instead of `int* p  = new(int);` the standard syntax is `int* p  = new int;`.

Assertions are very useful although I wouldn't describe these as a "tool for statement or unit testing" (can be used to support unit testing, however).
I can recommend the following:
- Use of Assertions: https://blog.regehr.org/archives/1091
- Assertions Are Pessimistic, Assumptions Are Optimistic: https://blog.regehr.org/archives/1096
- Logging, asserts and unit tests: http://tomforsyth1000.github.io/blog.wiki.html#%5B%5BLogging%2C%20asserts%20and%20unit%20tests%5D%5D

I also prefer to minimize any potential overlap to avoid redundancy--as far I can tell the topics are already extensively covered by the examples on https://en.cppreference.com/ (which I recommend as a general reference).

**Comment by seanvaleo** [comment]
Thank you for your consideration. I have applied your suggestions.
